import 'package:flutter_template/utils/app_string.dart';
import 'package:get/get.dart';

class ParameterSettingController extends GetxController {
  RxList settingList = [
    "designCapacity".tr,
    "fullCapacity".tr,
    AppString.covc,
    AppString.cov,
    AppString.cuvc,
    AppString.cuv,
    "batOverChargeRelease".tr,
    "batOverDischargeRelease".tr,
    "batOverCharge".tr,
    "batOverDischarge".tr,
    AppString.otcc,
    AppString.otc,
    AppString.ctcc,
    AppString.ctc,
    AppString.otdc,
    AppString.otd,
    AppString.utdc,
    AppString.utd,
    "taperCurrent".tr,
    "designVoltage".tr,
    "packLowVoltage".tr,
    "fullVoltage".tr,
  ].obs;

  RxList voltageList = [
    "3561",
    "10",
    "4.2",
    "4.25",
    "3.0",
    "2.7",
    "3561",
    "12.0",
    "17.0",
    "10.8",
    "55",
    "60",
    "-5",
    "0",
    "70",
    "75",
    "-15",
    "-20",
    "9.999",
    "14.4",
    "10.8",
    "16.4",
  ].obs;

  RxList unitList = [
    "mV",
    "AH",
    "V",
    "V",
    "V",
    "V",
    "mV",
    "V",
    "V",
    "V",
    "'C",
    "'C",
    "'C",
    "'C",
    "'C",
    "'C",
    "'C",
    "'C",
    "A",
    "V",
    "V",
    "V",
  ].obs;
}
